<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<Nullable>enable</Nullable>
		<TargetFramework>net9.0</TargetFramework>
		<!--<ImplicitUsings>enable</ImplicitUsings>-->
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Shared\Shared.csproj" />
		<ProjectReference Include="..\Resources\Resources.csproj" />
	</ItemGroup>

</Project>
